GET http://localhost:3000/api/list

###

GET http://localhost:3000/api/list/5e826756039bb216789e10b8

###

POST http://localhost:3000/api/list
Content-Type: application/json

{
  "member": "5e8266f0039bb216789e10b7",
  "offerings": [
    {
    "name": "5e826756039bb216789e10b8",
    "quantity": 10
    },
    {
    "name": "5e8159de3696d80830a28c78",
    "quantity": 20
    }
  ]
}

###

PUT http://localhost:3000/api/list/5d295f53775f250ed4c5240b
Content-Type: application/json

{
  "quantity": 50
}

###

DELETE  http://localhost:3000/api/list/
Content-Type: application/json

{
  "id": "5e83aecb0bad68003c29f51b"
}