
GET http://localhost:3000/api/members

###

GET http://localhost:3000/api/members/5e815986d6d59e0bdcb4fda6
Content-Type: application/json

{
  "id": "5e8151bd645ccf04b49c159a"
}

###

POST http://localhost:3000/api/members
Content-Type: application/json

{
  //"nombre": "Daniel Andrés Batista Alvarado"
  "nombre": "Brian Iván Zaragoza Fierro"
}

###

PUT http://localhost:3000/api/members
Content-Type: application/json

{
  "id": "5e813f471570d22368bdfe05",
  "name": "Brian Iván Zaragoza Fierro"
}

###

DELETE http://localhost:3000/api/members
Content-Type: application/json

{
  "id": "5e81590f03dde51a1cacbb8b"
}
 

