
GET http://localhost:3000/api/offering

###
POST http://localhost:3000/api/offering
Content-Type: application/json

{
  "name": "Programa"
}

###

PUT http://localhost:3000/api/offering
Content-Type: application/json

{
  "id": "5d47652884e2b421e877d257",
  "name": "Sociedad de Jóvenes"
}

###

DELETE http://localhost:3000/api/offering
Content-Type: application/json

{
  "id": "5d47655584e2b421e877d258"
}